### ISSUE TITLE
woocommerce_emails_attach_downloadables() must be an instance of WC_Order

### ISSUE THREAD

**Issue by mwangiwambui** [osenco/osen-wc-mpesa#60]
Getting the below error due to woocommerce conflicting with the mpesa plugin. This conflict makes the registration and forget password functionality not work on my wordpress website. See full error log below:

2023-04-10T17:11:53+00:00 CRITICAL Uncaught TypeError: Argument 3 passed to Osen\Woocommerce\Utilities::woocommerce_emails_attach_downloadables() must be an instance of WC_Order, instance of WP_User given, called in /home/site/public_html/wp-includes/class-wp-hook.php on line 310 and defined in /home/site/public_html/wp-content/plugins/osen-wc-mpesa-3.0.1rc/src/Utilities.php:110
Stack trace:
#0 /home/site/public_html/wp-includes/class-wp-hook.php(310): Osen\Woocommerce\Utilities->woocommerce_emails_attach_downloadables(Array, 'customer_reset_...', Object(WP_User))
#1 /home/site/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /home/site/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(461): apply_filters('woocommerce_ema...', Array, 'customer_reset_...', Object(WP_User), Object(WC_Email_Customer_Reset_Password))
#3 /home/site/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email-customer-reset-password.php(114): WC_Email->get_attachme in /home/site/public_html/wp-content/plugins/osen-wc-mpesa-3.0.1rc/src/Utilities.php on line 110

**Comment by maukoese** [comment]
I'll try update the code here, but meantime try downloading from the source.

**Comment by edwanyoike** [comment]
@mwangiwambui  were you able to fix this?

**Comment by maukoese** [comment]
Everything should be working fine now.

**Comment by edwanyoike** [comment]
hey @maukoese did you push a commit?
